### Add new amenity
POST http://localhost:8080/amenity/add
Content-Type: application/json

{
  "name": "Cut hair-",
  "description": "No description",
  "price": 100,
  "duration": "00:30:00"
}

### Return amenity by id
GET http://localhost:8080/amenity/getById/12

### Return all exist amenities
GET http://localhost:8080/amenity/getAll

### Update amenity
PUT http://localhost:8080/amenity/updateAmenity/11
Content-Type: application/json

{
  "name": "cut hair-"
}

### Delete amenity
DELETE http://localhost:8080/amenity/deleteAmenity/11

### Return avg price of all amenities
GET http://localhost:8080/amenity/avg