### Create new barber
POST http://localhost:8080/barber/create
Content-Type: application/json

{
  "phone": "barberPhone1",
  "email": "barberEmail1",
  "barberStatus": "WORK"
}

### Change barber status via id and status
PUT http://localhost:8080/barber/change?status=vacation&id=3
Content-Type: application/x-www-form-urlencoded

### Get avg rating for current barber
GET http://localhost:8080/barber/average-rating?barberId=1