### Create new registration
# Что лучше body или param?
# Имеет ли смысл model view?
POST http://localhost:8080/reg/create
Content-Type: application/json

{
  "time": "10:01",
  "day": "2024-01-01",
  "client": {"id": 1},
  "barber": {"id": 1}
}

### Read registration
PUT http://localhost:8080/reg/read?day=2024-01-01&time=10:00&barberId=1
Content-Type: application/x-www-form-urlencoded

### Delete registration
PUT http://localhost:8080/reg/delete?day=2024-01-01&time=10:00&barberId=1
Content-Type: application/x-www-form-urlencoded

